"""Markdown incident report generator.

Produces analyst-ready Markdown reports using Jinja2 templates.
Markdown is preferred for ticketing systems, wikis, and incident channels
where rendering is handled downstream.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from jinja2 import Environment, select_autoescape

from enricher.models import AttackCampaign, RiskScore, Severity
from enricher.reporters.base import BaseReporter


SEVERITY_EMOJI = {
    Severity.CRITICAL: "🔴",
    Severity.HIGH: "🟠",
    Severity.MEDIUM: "🟡",
    Severity.LOW: "🟢",
    Severity.INFO: "⚪",
}


MARKDOWN_TEMPLATE = """# 🚨 Security Incident Report

**Generated:** {{ generated_at.strftime('%Y-%m-%d %H:%M:%S UTC') }}
**Total IOCs Analyzed:** {{ stats.total_iocs }}
**Attack Campaigns Identified:** {{ stats.total_campaigns }}

---

## Executive Summary

{% if stats.critical_count > 0 -%}
**⚠️ {{ stats.critical_count }} critical-severity indicator(s) detected.** Immediate analyst review recommended.
{%- elif stats.high_count > 0 -%}
**{{ stats.high_count }} high-severity indicator(s) detected.** Review within standard SLA.
{%- else -%}
No critical or high-severity indicators found in this batch.
{%- endif %}

### Severity Distribution

| Severity | Count |
|---|---|
| 🔴 Critical | {{ stats.critical_count }} |
| 🟠 High | {{ stats.high_count }} |
| 🟡 Medium | {{ stats.medium_count }} |
| 🟢 Low | {{ stats.low_count }} |
| ⚪ Info | {{ stats.info_count }} |

---

## 🎯 Attack Campaigns

{% if campaigns -%}
{{ campaigns|length }} coordinated attack campaign(s) detected by grouping alerts from the same source IP within a 15-minute time window.

{% for campaign in campaigns[:10] %}
### Campaign {{ loop.index }}: {{ campaign.attacker_ip }}

- **Attacker IP:** `{{ campaign.attacker_ip }}`
- **Alert Count:** {{ campaign.alert_count }}
- **Duration:** {{ (campaign.end_time - campaign.start_time).total_seconds()|int }} seconds
- **Start:** {{ campaign.start_time.strftime('%Y-%m-%d %H:%M:%S UTC') }}
- **End:** {{ campaign.end_time.strftime('%Y-%m-%d %H:%M:%S UTC') }}
- **Top Signature:** {{ campaign.top_signature }}
- **Unique Signatures:** {{ campaign.signatures|length }}

**Triggered Signatures:**
{% for sig in campaign.signatures[:8] %}
- {{ sig }}
{%- endfor %}

{% endfor %}
{%- else -%}
No attack campaigns identified. Alerts appear isolated rather than coordinated.
{%- endif %}

---

## 🔍 Top Scored Indicators of Compromise

{% if top_iocs -%}
| Rank | Severity | Score | IOC | Type | Sources | Flags |
|---|---|---|---|---|---|---|
{% for score in top_iocs -%}
| {{ loop.index }} | {{ severity_emoji[score.severity] }} {{ score.severity.value|upper }} | {{ score.score }} | `{{ score.ioc.value }}` | {{ score.ioc.type.value }} | {{ score.sources_reporting }} | {{ score.malicious_sources }} malicious |
{% endfor %}
{% else -%}
No IOCs met the scoring threshold for this report.
{% endif %}

---

## 📊 Enrichment Details

{% for score in top_iocs[:5] %}
### {{ severity_emoji[score.severity] }} {{ score.ioc.value }}

- **Type:** `{{ score.ioc.type.value }}`
- **Final Score:** `{{ score.score }}/100` ({{ score.severity.value|upper }})
- **Sources Reporting:** {{ score.sources_reporting }}
- **Malicious Verdicts:** {{ score.malicious_sources }}/{{ score.sources_reporting }}

**Source Breakdown:**

| Source | Malicious | Confidence | Categories |
|---|---|---|---|
{% for e in score.enrichments -%}
| {{ e.source }} | {{ '✓' if e.malicious else '✗' }} | {{ '%.0f%%'|format(e.confidence * 100) }} | {{ e.categories[:3]|join(', ') if e.categories else '—' }} |
{% endfor %}

{% endfor %}

---

## 📎 Report Metadata

- **Generated by:** threat-intel-enricher v0.1.0
- **Analysis Time (UTC):** {{ generated_at.strftime('%Y-%m-%d %H:%M:%S') }}
- **Data Sources:** AbuseIPDB, URLhaus, AlienVault OTX

*For questions or to refine detection rules, contact the Security Operations team.*
"""


class MarkdownReporter(BaseReporter):
    """Generate analyst-ready Markdown incident reports."""

    name = "markdown"
    file_extension = "md"

    def __init__(self) -> None:
        self.env = Environment(
            autoescape=select_autoescape(["html", "xml"], disabled_extensions=["md"]),
            trim_blocks=True,
            lstrip_blocks=True,
        )
        self.template = self.env.from_string(MARKDOWN_TEMPLATE)

    def render(
        self,
        scores: list[RiskScore],
        campaigns: list[AttackCampaign],
    ) -> str:
        return self.template.render(
            generated_at=datetime.now(timezone.utc),
            campaigns=campaigns,
            top_iocs=scores[:20],
            stats=_calculate_stats(scores, campaigns),
            severity_emoji=SEVERITY_EMOJI,
        )


def _calculate_stats(scores: list[RiskScore], campaigns: list[AttackCampaign]) -> dict[str, Any]:
    """Compute summary statistics for the executive summary section."""
    by_severity: dict[Severity, int] = {s: 0 for s in Severity}
    for score in scores:
        by_severity[score.severity] += 1

    return {
        "total_iocs": len(scores),
        "total_campaigns": len(campaigns),
        "critical_count": by_severity[Severity.CRITICAL],
        "high_count": by_severity[Severity.HIGH],
        "medium_count": by_severity[Severity.MEDIUM],
        "low_count": by_severity[Severity.LOW],
        "info_count": by_severity[Severity.INFO],
    }
